language: node_js
dist: trusty
node_js: lts/*

branches:
  only:
    - master

notifications:
  email:
    on_success: never

before_install:
  - npm i -g greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update

script:
  - npm run test

after_script:
  - greenkeeper-lockfile-upload
