sudo: false
language: node_js
node_js:
  - node

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_install:
  - npm update
install:
  - npm install
script:
  - npm run test
  - npm run test:coveralls
  - npm run prepublish

deploy:
  provider: npm
  email: EMAIL_ADDRESS
  api_key: AUTH_TOKEN
  on:
    branch: master
  skip_cleanup: true

notification:
  email: false
